spring:
  application:
    name: snippet-permission
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:db-permissions}
    username: sa
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI:https://dev-dxazwu1rijz501rx.us.auth0.com/}
          client-id: ${AUTH_CLIENT_ID:client-id}
          client-secret: ${AUTH_CLIENT_SECRET:client-secret}
auth0:
  audience: ${AUTH0_AUDIENCE:https://snippet-searcher}


server:
  port: 8083
